"""
Mapping form Pinyin to IPA (Phonemes)
Reference: https://en.wikipedia.org/wiki/Help:IPA/Mandarin
Target IPAs must be in phoneme_to_viseme.py
"""

# Dynamic mapping: Initials + Finals to create movement.
# Initial -> Final (Main Vowel)

pinyin_to_ipa_map = {
    # A
    "a": ["a"],
    "ai": ["a", "i"],
    "an": ["a", "n"],
    "ang": ["a", "ŋ"],
    "ao": ["a", "ʊ"],
    # B (Initial 'b' -> PP[7], Final)
    "ba": ["b", "a"],
    "bai": ["b", "a", "i"],
    "ban": ["b", "a", "n"],
    "bang": ["b", "a", "ŋ"],
    "bao": ["b", "a", "ʊ"],
    "bei": ["b", "e"],
    "ben": ["b", "e", "n"],
    "beng": ["b", "e", "ŋ"],
    "bi": ["b", "i"],
    "bian": ["b", "i", "a", "n"],
    "biao": ["b", "i", "a", "ʊ"],
    "bie": ["b", "i", "e"],
    "bin": ["b", "i", "n"],
    "bing": ["b", "i", "ŋ"],
    "bo": ["b", "o"],
    "bu": ["b", "u"],
    # C (Initial 'c' -> s[6]/t[6], Final)
    "ca": ["s", "a"],
    "cai": ["s", "a", "i"],
    "can": ["s", "a", "n"],
    "cang": ["s", "a", "ŋ"],
    "cao": ["s", "a", "ʊ"],
    "ce": ["s", "e"],
    "cen": ["s", "e", "n"],
    "ceng": ["s", "e", "ŋ"],
    "cha": ["tʃ", "a"],
    "chai": ["tʃ", "a", "i"],
    "chan": ["tʃ", "a", "n"],
    "chang": ["tʃ", "a", "ŋ"],
    "chao": ["tʃ", "a", "ʊ"],
    "che": ["tʃ", "e"],
    "chen": ["tʃ", "e", "n"],
    "cheng": ["tʃ", "e", "ŋ"],
    "chi": ["tʃ", "i"],
    "chong": ["tʃ", "o", "ŋ"],
    "chou": ["tʃ", "o", "u"],
    "chu": ["tʃ", "u"],
    "chua": ["tʃ", "u", "a"],
    "chuai": ["tʃ", "u", "a", "i"],
    "chuan": ["tʃ", "u", "a", "n"],
    "chuang": ["tʃ", "u", "a", "ŋ"],
    "chui": ["tʃ", "u", "e"],
    "chun": ["tʃ", "u", "n"],
    "chuo": ["tʃ", "u", "o"],
    "ci": ["s", "i"],
    "cong": ["s", "o", "ŋ"],
    "cou": ["s", "o", "u"],
    "cu": ["s", "u"],
    "cuan": ["s", "u", "a", "n"],
    "cui": ["s", "u", "e"],
    "cun": ["s", "u", "n"],
    "cuo": ["s", "u", "o"],
    # D (Initial 'd' -> DD[6], Final)
    "da": ["d", "a"],
    "dai": ["d", "a", "i"],
    "dan": ["d", "a", "n"],
    "dang": ["d", "a", "ŋ"],
    "dao": ["d", "a", "ʊ"],
    "de": ["d", "e"],
    "dei": ["d", "e"],
    "deng": ["d", "e", "ŋ"],
    "di": ["d", "i"],
    "dian": ["d", "i", "a", "n"],
    "diao": ["d", "i", "a", "ʊ"],
    "die": ["d", "i", "e"],
    "ding": ["d", "i", "ŋ"],
    "diu": ["d", "i", "u"],
    "dong": ["d", "o", "ŋ"],
    "dou": ["d", "o", "u"],
    "du": ["d", "u"],
    "duan": ["d", "u", "a", "n"],
    "dui": ["d", "u", "e"],
    "dun": ["d", "u", "n"],
    "duo": ["d", "u", "o"],
    # E
    "e": ["e"],
    "ei": ["e", "i"],
    "en": ["e", "n"],
    "eng": ["e", "ŋ"],
    "er": ["a", "r"],
    # F (Initial 'f' -> FF[7], Final)
    "fa": ["f", "a"],
    "fan": ["f", "a", "n"],
    "fang": ["f", "a", "ŋ"],
    "fei": ["f", "e"],
    "fen": ["f", "e", "n"],
    "feng": ["f", "e", "ŋ"],
    "fo": ["f", "o"],
    "fou": ["f", "o", "u"],
    "fu": ["f", "u"],
    # G (Initial 'g' -> k[17] or g[6]? phoneme_to_viseme has `g`. Let's check keys.)
    # Keys for ID 6/DD: d, t, n, l, h, s, z, ...
    # Wait, `phoneme_to_viseme`: `g` -> `kk`(17).
    # `k` -> `kk`(17).
    # Use `g` for unvoiced, `k` for voiced/aspirated?
    # Pinyin `g` is /k/ (unaspirated). `k` is /kʰ/ (aspirated).
    # Both map to `kk` (17).
    # 17 is usually Back/Velar.
    "ga": ["g", "a"],
    "gai": ["g", "a", "i"],
    "gan": ["g", "a", "n"],
    "gang": ["g", "a", "ŋ"],
    "gao": ["g", "a", "ʊ"],
    "ge": ["g", "e"],
    "gei": ["g", "e"],
    "gen": ["g", "e", "n"],
    "geng": ["g", "e", "ŋ"],
    "gong": ["g", "o", "ŋ"],
    "gou": ["g", "o", "u"],
    "gu": ["g", "u"],
    "gua": ["g", "u", "a"],
    "guai": ["g", "u", "a", "i"],
    "guan": ["g", "u", "a", "n"],
    "guang": ["g", "u", "a", "ŋ"],
    "gui": ["g", "u", "e"],
    "gun": ["g", "u", "n"],
    "guo": ["g", "u", "o"],
    # H (Initial 'h' -> DD[6])
    "ha": ["h", "a"],
    "hai": ["h", "a", "i"],
    "han": ["h", "a", "n"],
    "hang": ["h", "a", "ŋ"],
    "hao": ["h", "a", "ʊ"],
    "he": ["h", "e"],
    "hei": ["h", "e"],
    "hen": ["h", "e", "n"],
    "heng": ["h", "e", "ŋ"],
    "hong": ["h", "o", "ŋ"],
    "hou": ["h", "o", "u"],
    "hu": ["h", "u"],
    "hua": ["h", "u", "a"],
    "huai": ["h", "u", "a", "i"],
    "huan": ["h", "u", "a", "n"],
    "huang": ["h", "u", "a", "ŋ"],
    "hui": ["h", "u", "e"],
    "hun": ["h", "u", "n"],
    "huo": ["h", "u", "o"],
    # J (Initial 'j' -> CH[8])
    "ji": ["dʒ", "i"],
    "jia": ["dʒ", "i", "a"],
    "jian": ["dʒ", "i", "a", "n"],
    "jiang": ["dʒ", "i", "a", "ŋ"],
    "jiao": ["dʒ", "i", "a", "ʊ"],
    "jie": ["dʒ", "i", "e"],
    "jin": ["dʒ", "i", "n"],
    "jing": ["dʒ", "i", "ŋ"],
    "jiong": ["dʒ", "i", "o", "ŋ"],
    "jiu": ["dʒ", "i", "u"],
    "ju": ["dʒ", "y"],
    "juan": ["dʒ", "y", "a", "n"],
    "jue": ["dʒ", "y", "e"],
    "jun": ["dʒ", "y", "n"],
    # K (Initial 'k' -> kk[17])
    "ka": ["k", "a"],
    "kai": ["k", "a", "i"],
    "kan": ["k", "a", "n"],
    "kang": ["k", "a", "ŋ"],
    "kao": ["k", "a", "ʊ"],
    "ke": ["k", "e"],
    "kei": ["k", "e"],
    "ken": ["k", "e", "n"],
    "keng": ["k", "e", "ŋ"],
    "kong": ["k", "o", "ŋ"],
    "kou": ["k", "o", "u"],
    "ku": ["k", "u"],
    "kua": ["k", "u", "a"],
    "kuai": ["k", "u", "a", "i"],
    "kuan": ["k", "u", "a", "n"],
    "kuang": ["k", "u", "a", "ŋ"],
    "kui": ["k", "u", "e"],
    "kun": ["k", "u", "n"],
    "kuo": ["k", "u", "o"],
    # L (Initial 'l' -> nn[6] or DD?)
    # `phoneme_to_viseme`: `l` -> `nn` (6).
    "la": ["l", "a"],
    "lai": ["l", "a", "i"],
    "lan": ["l", "a", "n"],
    "lang": ["l", "a", "ŋ"],
    "lao": ["l", "a", "ʊ"],
    "le": ["l", "e"],
    "lei": ["l", "e"],
    "leng": ["l", "e", "ŋ"],
    "li": ["l", "i"],
    "lia": ["l", "i", "a"],
    "lian": ["l", "i", "a", "n"],
    "liang": ["l", "i", "a", "ŋ"],
    "liao": ["l", "i", "a", "ʊ"],
    "lie": ["l", "i", "e"],
    "lin": ["l", "i", "n"],
    "ling": ["l", "i", "ŋ"],
    "liu": ["l", "i", "u"],
    "long": ["l", "o", "ŋ"],
    "lou": ["l", "o", "u"],
    "lu": ["l", "u"],
    "lv": ["l", "y"],
    "luan": ["l", "u", "a", "n"],
    "lue": ["l", "y", "e"],
    "lve": ["l", "y", "e"],
    "lun": ["l", "u", "n"],
    "luo": ["l", "u", "o"],
    # M (Initial 'm' -> PP[7])
    "ma": ["m", "a"],
    "mai": ["m", "a", "i"],
    "man": ["m", "a", "n"],
    "mang": ["m", "a", "ŋ"],
    "mao": ["m", "a", "ʊ"],
    "me": ["m", "e"],
    "mei": ["m", "e"],
    "men": ["m", "e", "n"],
    "meng": ["m", "e", "ŋ"],
    "mi": ["m", "i"],
    "mian": ["m", "i", "a", "n"],
    "miao": ["m", "i", "a", "ʊ"],
    "mie": ["m", "i", "e"],
    "min": ["m", "i", "n"],
    "ming": ["m", "i", "ŋ"],
    "miu": ["m", "i", "u"],
    "mo": ["m", "o"],
    "mou": ["m", "o", "u"],
    "mu": ["m", "u"],
    # N (Initial 'n' -> nn[6])
    "na": ["n", "a"],
    "nai": ["n", "a", "i"],
    "nan": ["n", "a", "n"],
    "nang": ["n", "a", "ŋ"],
    "nao": ["n", "a", "ʊ"],
    "ne": ["n", "e"],
    "nei": ["n", "e"],
    "nen": ["n", "e", "n"],
    "neng": ["n", "e", "ŋ"],
    "ni": ["n", "i"],
    "nian": ["n", "i", "a", "n"],
    "niang": ["n", "i", "a", "ŋ"],
    "niao": ["n", "i", "a", "ʊ"],
    "nie": ["n", "i", "e"],
    "nin": ["n", "i", "n"],
    "ning": ["n", "i", "ŋ"],
    "niu": ["n", "i", "u"],
    "nong": ["n", "o", "ŋ"],
    "nou": ["n", "o", "u"],
    "nu": ["n", "u"],
    "nv": ["n", "y"],
    "nuan": ["n", "u", "a", "n"],
    "nue": ["n", "y", "e"],
    "nve": ["n", "y", "e"],
    "nun": ["n", "u", "n"],
    "nuo": ["n", "u", "o"],
    # O
    "o": ["o"],
    "ou": ["o", "u"],
    # P (Initial 'p' -> PP[7])
    "pa": ["p", "a"],
    "pai": ["p", "a", "i"],
    "pan": ["p", "a", "n"],
    "pang": ["p", "a", "ŋ"],
    "pao": ["p", "a", "ʊ"],
    "pei": ["p", "e"],
    "pen": ["p", "e", "n"],
    "peng": ["p", "e", "ŋ"],
    "pi": ["p", "i"],
    "pian": ["p", "i", "a", "n"],
    "piao": ["p", "i", "a", "ʊ"],
    "pie": ["p", "i", "e"],
    "pin": ["p", "i", "n"],
    "ping": ["p", "i", "ŋ"],
    "po": ["p", "o"],
    "pou": ["p", "o", "u"],
    "pu": ["p", "u"],
    # Q (Initial 'q' -> CH[8])
    "qi": ["tʃ", "i"],
    "qia": ["tʃ", "i", "a"],
    "qian": ["tʃ", "i", "a", "n"],
    "qiang": ["tʃ", "i", "a", "ŋ"],
    "qiao": ["tʃ", "i", "a", "ʊ"],
    "qie": ["tʃ", "i", "e"],
    "qin": ["tʃ", "i", "n"],
    "qing": ["tʃ", "i", "ŋ"],
    "qiong": ["tʃ", "i", "o", "ŋ"],
    "qiu": ["tʃ", "i", "u"],
    "qu": ["tʃ", "y"],
    "quan": ["tʃ", "y", "a", "n"],
    "que": ["tʃ", "y", "e"],
    "qun": ["tʃ", "y", "n"],
    # R (Initial 'r' -> RR[7] -> Viseme 6 is `RR`? Wait, RR is 7 in map.json.
    # `phoneme_to_viseme`: `r` -> `RR`. `RR` is 7.
    # If `r` is 7, `ran` (7 -> a/7) is static?
    # `r` in English is round lips (7). in Chinese it's retroflex /ʐ/.
    # Can we map `r` to something else? or `raw` is fine.
    # Viseme Map: `RR` is 7 in `viseme_map.json`. 3 in `viseme_map2.json`.
    # Let's trust `RR` -> 7.
    "ran": ["r", "a", "n"],
    "rang": ["r", "a", "ŋ"],
    "rao": ["r", "a", "ʊ"],
    "re": ["r", "e"],
    "ren": ["r", "e", "n"],
    "reng": ["r", "e", "ŋ"],
    "ri": ["r", "i"],
    "rong": ["r", "o", "ŋ"],
    "rou": ["r", "o", "u"],
    "ru": ["r", "u"],
    "ruan": ["r", "u", "a", "n"],
    "rui": ["r", "u", "e"],
    "run": ["r", "u", "n"],
    "ruo": ["r", "u", "o"],
    # S (Initial 's' -> SS[6])
    "sa": ["s", "a"],
    "sai": ["s", "a", "i"],
    "san": ["s", "a", "n"],
    "sang": ["s", "a", "ŋ"],
    "sao": ["s", "a", "ʊ"],
    "se": ["s", "e"],
    "sen": ["s", "e", "n"],
    "seng": ["s", "e", "ŋ"],
    "sha": ["ʃ", "a"],
    "shai": ["ʃ", "a", "i"],
    "shan": ["ʃ", "a", "n"],
    "shang": ["ʃ", "a", "ŋ"],
    "shao": ["ʃ", "a", "ʊ"],
    "she": ["ʃ", "e"],
    "shei": ["ʃ", "e"],
    "shen": ["ʃ", "e", "n"],
    "sheng": ["ʃ", "e", "ŋ"],
    "shi": ["ʃ", "i"],
    "shou": ["ʃ", "o", "u"],
    "shu": ["ʃ", "u"],
    "shua": ["ʃ", "u", "a"],
    "shuai": ["ʃ", "u", "a", "i"],
    "shuan": ["ʃ", "u", "a", "n"],
    "shuang": ["ʃ", "u", "a", "ŋ"],
    "shui": ["ʃ", "u", "e"],
    "shun": ["ʃ", "u", "n"],
    "shuo": ["ʃ", "u", "o"],
    "si": ["s", "i"],
    "song": ["s", "o", "ŋ"],
    "sou": ["s", "o", "u"],
    "su": ["s", "u"],
    "suan": ["s", "u", "a", "n"],
    "sui": ["s", "u", "e"],
    "sun": ["s", "u", "n"],
    "suo": ["s", "u", "o"],
    # T (Initial 't' -> DD[6])
    "ta": ["t", "a"],
    "tai": ["t", "a", "i"],
    "tan": ["t", "a", "n"],
    "tang": ["t", "a", "ŋ"],
    "tao": ["t", "a", "ʊ"],
    "te": ["t", "e"],
    "teng": ["t", "e", "ŋ"],
    "ti": ["t", "i"],
    "tian": ["t", "i", "a", "n"],
    "tiao": ["t", "i", "a", "ʊ"],
    "tie": ["t", "i", "e"],
    "ting": ["t", "i", "ŋ"],
    "tong": ["t", "o", "ŋ"],
    "tou": ["t", "o", "u"],
    "tu": ["t", "u"],
    "tuan": ["t", "u", "a", "n"],
    "tui": ["t", "u", "e"],
    "tun": ["t", "u", "n"],
    "tuo": ["t", "u", "o"],
    # W (Initial 'w' -> ou[7]?)
    # `phoneme_to_viseme`: `w` -> `ou` (7).
    "wa": ["w", "a"],
    "wai": ["w", "a", "i"],
    "wan": ["w", "a", "n"],
    "wang": ["w", "a", "ŋ"],
    "wei": ["w", "e"],
    "wen": ["w", "e", "n"],
    "weng": ["w", "e", "ŋ"],
    "wo": ["w", "o"],
    "wu": ["u"],
    # X (Initial 'x' -> SS[6]) - `x` is `DD` in map? `phoneme_to_viseme`: `x` -> `DD`.
    # Pinyin `x` is /ɕ/. `ɕ` -> `SS` (6).
    # Correct.
    "xi": ["ɕ", "i"],
    "xia": ["ɕ", "i", "a"],
    "xian": ["ɕ", "i", "a", "n"],
    "xiang": ["ɕ", "i", "a", "ŋ"],
    "xiao": ["ɕ", "i", "a", "ʊ"],
    "xie": ["ɕ", "i", "e"],
    "xin": ["ɕ", "i", "n"],
    "xing": ["ɕ", "i", "ŋ"],
    "xiong": ["ɕ", "i", "o", "ŋ"],
    "xiu": ["ɕ", "i", "u"],
    "xu": ["ɕ", "y"],
    "xuan": ["ɕ", "y", "a", "n"],
    "xue": ["ɕ", "y", "e"],
    "xun": ["ɕ", "y", "n"],
    # Y (Initial 'y' -> DD[6])
    # `y` -> `DD` (6).
    "ya": ["j", "a"],
    "yan": ["j", "a", "n"],
    "yang": ["j", "a", "ŋ"],
    "yao": ["j", "a", "ʊ"],
    "ye": ["j", "e"],
    "yi": ["i"],
    "yin": ["i", "n"],
    "ying": ["i", "ŋ"],
    "yo": ["j", "o"],
    "yong": ["j", "o", "ŋ"],
    "you": ["j", "o", "u"],
    "yu": ["y"],
    "yuan": ["y", "a", "n"],
    "yue": ["y", "e"],
    "yun": ["y", "n"],
    # Z (Initial 'z' -> SS[6])
    "za": ["z", "a"],
    "zai": ["z", "a", "i"],
    "zan": ["z", "a", "n"],
    "zang": ["z", "a", "ŋ"],
    "zao": ["z", "a", "ʊ"],
    "ze": ["z", "e"],
    "zei": ["z", "e"],
    "zen": ["z", "e", "n"],
    "zeng": ["z", "e", "ŋ"],
    "zha": ["dʒ", "a"],
    "zhai": ["dʒ", "a", "i"],
    "zhan": ["dʒ", "a", "n"],
    "zhang": ["dʒ", "a", "ŋ"],
    "zhao": ["dʒ", "a", "ʊ"],
    "zhe": ["dʒ", "e"],
    "zhei": ["dʒ", "e"],
    "zhen": ["dʒ", "e", "n"],
    "zheng": ["dʒ", "e", "ŋ"],
    "zhi": ["dʒ", "i"],
    "zhong": ["dʒ", "o", "ŋ"],
    "zhou": ["dʒ", "o", "u"],
    "zhu": ["dʒ", "u"],
    "zhua": ["dʒ", "u", "a"],
    "zhuai": ["dʒ", "u", "a", "i"],
    "zhuan": ["dʒ", "u", "a", "n"],
    "zhuang": ["dʒ", "u", "a", "ŋ"],
    "zhui": ["dʒ", "u", "e"],
    "zhun": ["dʒ", "u", "n"],
    "zhuo": ["dʒ", "u", "o"],
    "zi": ["z", "i"],
    "zong": ["z", "o", "ŋ"],
    "zou": ["z", "o", "u"],
    "zu": ["z", "u"],
    "zuan": ["z", "u", "a", "n"],
    "zui": ["z", "u", "e"],
    "zun": ["z", "u", "n"],
    "zuo": ["z", "u", "o"],
}


def convert_pinyin_to_phonemes(pinyin: str) -> list[str]:
    # Handle tone numbers if present (e.g. zha1 -> zha)
    clean_pinyin = "".join([c for c in pinyin if c.isalpha()]).lower()
    return pinyin_to_ipa_map.get(clean_pinyin, [])
